include "application.conf"

slick.dbs.default.db {
  url = "jdbc:clickhouse://platform.gtd.thehyve.nl:8123"
  url = ${?SLICK_CLICKHOUSE_URL}
  user = "default"
  password = ${?SLICK_CLICKHOUSE_PASSWORD}
}

ot.elasticsearch.host = "platform.gtd.thehyve.nl"
ot.elasticsearch.host = ${?ELASTICSEARCH_HOST}

ot.meta.apiVersion = "26.03.0"
ot.meta.apiVersion = ${?META_API_VERSION}
